### ISSUE TITLE
Issue with "PAN Device Framework Quickstart" in @site/docs/apis/pandevice_qs.md

### ISSUE THREAD

**Issue by sserrata** [PaloAltoNetworks/panos.pan.dev#164]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

Broken "Usage guide" link.

## Suggested fix

Change to correct link URL.

**Comment by sserrata** [comment]
Hi @btorresgil, thanks for reporting this issue. I was wondering how you wanted to proceed?

**Comment by btorresgil** [comment]
I think this was just a broken link. This was probably a quick note to myself but I can’t recall. I’ll close it for now until I know what link it was about.
