### ISSUE TITLE
Issue with "Automating IP Blocking" in @site/docs/apis/panos_dag_qs.md

### ISSUE THREAD

**Issue by sserrata** [PaloAltoNetworks/panos.pan.dev#166]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

Broken links to other docs.

## Suggested fix

Update links.

**Comment by fvigo** [comment]
@sserrata what links are broken? Were the urls changed?

**Comment by sserrata** [comment]
Yes, the doc `dir` structure was changed, so basically any reference to another doc needs to be updated. I can help work on it later.

**Comment by fvigo** [comment]
I think I fixed it with #168

**Comment by sserrata** [comment]
Issue resolved - thanks!
