### ISSUE TITLE
"Products" position in the topbars

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/panos.pan.dev#182]
The `Products` menu in the topbar is in different positions in cortex.pan.dev, panos.pan.dev and xsoar.pan.dev. Position should be consistent across the websites.

**Comment by sserrata** [comment]
Should the `Products` menu occupy the same absolute or relative position in the nav bar? For example, should it always be the "left-most" option (regardless of the number of items to the right) or should it always be immediately to the left of the `Blog` item, as follows:

`Products` <-> `Blog` <-> `GitHub`

**Comment by sserrata** [comment]
@jtschichold Just following up. Please see previous message for my follow up question.

**Comment by jtschichold** [comment]
@sserrata do you think would be possible to make the `Products` menu appear when the site brand icon is hovered?

**Comment by sserrata** [comment]
Yes, I think it should be possible. I'll experiment and submit a PR so we
can preview.

--Steven
