### ISSUE TITLE
Issue with "Terraform ELB Integration" in @site/docs/cloud/terraform_elb.md

### ISSUE THREAD

**Issue by chiranjeev2019** [PaloAltoNetworks/panos.pan.dev#189]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

when I run the script prep_tf.py it gives the error. 

Traceback (most recent call last):
  File "C:\Users\Chiranjeev Sinha\Desktop\terraform\palo alto autoscale\aws_modules_version\prep_tf.py", line 70, in <module>
    main()
  File "C:\Users\Chiranjeev Sinha\Desktop\terraform\palo alto autoscale\aws_modules_version\prep_tf.py", line 48, in main
    key, value = line.split("=")
ValueError: need more than 1 value to unpack

I'm new to python so I don't understand what is this error. I tried to google it but no luck.
I am using it to generate terraform.tfvars from output.tfvars. 
Could you please help me on this.

2nd. when I make terraform.tfvars manually and run terraform apply: it gives me below error: 
terraform.exe plan

Error: resource 'aws_cloudformation_stack.LambdaCustomResource' config: unknown variable referenced: 'LambdaENIQueue'; define it with a 'variable' block

Error: resource 'aws_cloudformation_stack.LambdaCustomResource' config: unknown variable referenced: 'UntrustSecurityGroup'; define it with a 'variable' block

Error: resource 'aws_cloudformation_stack.LambdaCustomResource' config: unknown variable referenced: 'TrustSecurityGroup'; define it with a 'variable' block

Error: resource 'aws_cloudformation_stack.LambdaCustomResource' config: unknown variable referenced: 'MgmtSecurityGroup'; define it with a 'variable' block

_______________________________________________
i have verified the variables are declared already.

**Comment by sserrata** [comment]
Hi @chiranjeev2019, were you able to resolve or get help for this issue?
