### ISSUE TITLE
Issue with "Expedition 2.0 Installation" in @site/docs/expedition/expedition_qs.md

### ISSUE THREAD

**Issue by smdicicco** [PaloAltoNetworks/panos.pan.dev#239]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

The installation script check for expedition being already installed utilizes the wrong command to list applications and therefore never recognizes expedition as installed.

## Suggested fix

Utilize "apt list --installed" instead of "apt-get list --installed"

# Check if some packages has already been installed
    expeditionAlreadyInstalled=$(apt list --installed | grep -c expedition)
    if [ "$expeditionAlreadyInstalled" -ne 0 ]; then
        printTitleFailed "This script has been prepared to install Expedition from scratch"
        printTitleFailed "Expedition package is already present"
        exit 1
    else
        printTitle "This machine does not have Expedition installed"
    fi;

**Comment by dgildelaig** [comment]
Got it. 
Prepared for the next installation script.
