### ISSUE TITLE
Incorrect Python Example for Expedition Zip Preparation

### ISSUE THREAD

**Issue by tbailey25** [PaloAltoNetworks/panos.pan.dev#281]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

The python example for `STEP 1: Initiate a Zip preparation for migration` at the URL below is incorrect. In the response from the Expedition API the key under `expedition` is `resources`, not `resource` as listed in the documentation.

https://panos.pan.dev/docs/expedition/creating_migration_zip_2/

Relevant response data from the API.
```
      "data": {
        "total-objects": null,
        "fields": null,
        "columns": null,
        "content": {
          "expedition": {
            "resources": {
              "zipId": 860292
            }
          }
        }
```

## Suggested fix
```
--- a/docs/expedition/creating_migration_zip_2.mdx
+++ b/docs/expedition/creating_migration_zip_2.mdx
@@ -126,7 +126,7 @@ values={[
 print('PREPARE MIGRATION ZIP')
 r = requests.get('https://'+ip+'/api/v1/prepare/zip', data=data, verify=False, headers=hed)
 response=r.json()
-zipID = json.dumps(response['Contents']['response']['data']['content']['expedition']['resource']['zipId'])
+zipID = json.dumps(response['Contents']['response']['data']['content']['expedition']['resources']['zipId'])
 print(zipID+'\n')
```

**Comment by lychiang** [comment]
Hi [tbailey25](https://github.com/tbailey25), we are working on changing all the API syntax , so current example of API calls are no longer valid.  please wait until May, 2022 for beta testing.
